version: '3.9'
services:
  redis:
    image: redis
    ports:
      - '56379:6379'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hunted_user
      POSTGRES_PASSWORD: hunted123
      POSTGRES_DB: hunted
    ports:
      - '5432:5432'
